apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: dogukan-test
spec:
  type: ClusterIP
  selector:
    app: rag-api
  ports:
    - name: http
      port: 8080
      targetPort: http
